# Generated by Django 2.1.7 on 2019-02-22 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0003_mood'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mood',
            options={'ordering': ('-created_date',)},
        ),
    ]
